app:
  naver:
    client:
      id: [id]
      secret: [secret]
  classifier:
    url: [url]
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: [url]
    username: [username]
    password: [password]